language: rust

rust:
  - stable
  - beta
  - nightly

script:
  - cargo test
  - cargo test --features=complex-expressions

matrix:
  include:
    - name: "README.md doc test"
      rust: nightly
      script:
        - cargo test --features=external_doc --doc
    - name: "no-std build"
      rust: stable
      script:
        - rustup target add thumbv6m-none-eabi
        - cargo build --target=thumbv6m-none-eabi
